apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: data-historian-spc
  namespace: ${aio_cluster_namespace}
spec:
  provider: "azure"
  secretObjects:
    - secretName: grafana-secret
      type: Opaque
      data:
        - objectName: grafana-admin-password
          key: admin-password
        - objectName: grafana-admin-user
          key: admin-user
    - secretName: data-historian-secret
      type: Opaque
      data:
        - objectName: influxdb-admin-password
          key: admin-password
        - objectName: influxdb-admin-token
          key: admin-token
  parameters:
    usePodIdentity: "false"
    keyvaultName: "${key_vault_name}"
    objects: |
      array:
        - |
          objectName: influxdb-admin-password
          objectType: secret
          objectVersion: ""
        - |
          objectName: influxdb-admin-token
          objectType: secret
          objectVersion: ""
        - |
          objectName: grafana-admin-password
          objectType: secret
          objectVersion: ""
        - |
          objectName: grafana-admin-user
          objectType: secret
          objectVersion: ""
    tenantId: ${tenant_id}