apiVersion: v1
kind: Service
metadata:
  name: http-echo
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8443
  selector:
    app.kubernetes.io/name: http-echo
  type: ClusterIP
