apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-echo
  labels:
    app.kubernetes.io/name: http-echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: http-echo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: http-echo
    spec:
      containers:
        - name: http-echo
          image: ghcr.io/mendhak/http-https-echo:31
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 8443
              name: https