{
 "title": "Data Historian",
 "time": { "from": "now-2m", "to": "now" },
 "panels": [
  { "title": "Boiler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Boiler Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"default\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"aio/data/opc.tcp/opc.tcp-1/thermostat\")\n  |> filter(fn: (r) => r[\"CapabilityId\"] == \"dtmi:com:example:Thermostat;1:boilerStatus\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Value_Pressure\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Boiler Heater",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"default\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"aio/data/opc.tcp/opc.tcp-1/thermostat\")\n  |> filter(fn: (r) => r[\"CapabilityId\"] == \"dtmi:com:example:Thermostat;1:boilerStatus\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Value_HeaterState\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Boiler Temp Top/Bottom",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"default\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"aio/data/opc.tcp/opc.tcp-1/thermostat\")\n  |> filter(fn: (r) => r[\"CapabilityId\"] == \"dtmi:com:example:Thermostat;1:boilerStatus\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Value_Temperature_Bottom\" or r[\"_field\"] == \"Value_Temperature_Top\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  }
 ]
}