apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: telegraf
  labels:
    app.kubernetes.io/name: telegraf
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: telegraf