apiVersion: v1
kind: Service
metadata:
  name: telegraf
  labels:
    app.kubernetes.io/name: telegraf
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      name: generic
    - port: 8081
      targetPort: 8081
      name: opcua
    - port: 8888
      targetPort: 8888
      name: health
  selector:
    app.kubernetes.io/name: telegraf