apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
  labels:
    app.kubernetes.io/name: telegraf
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: telegraf
  template:
    metadata:
      labels:
        app.kubernetes.io/name: telegraf
      annotations:
        checksum/config: "${telegraf_conf_hash}"
    spec:
      containers:
        - name: telegraf
          image: docker.io/library/telegraf:1.29.2
          env:
            - name: HOSTNAME
              value: telegraf-service
            - name: INFLUXDB_TOKEN
              valueFrom:
                secretKeyRef:
                  key: admin-token
                  name: data-historian-secret
            - name: INFLUXDB_ORG
              value: datahistorian
            - name: INFLUXDB_BUCKET
              value: default
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 8888
              name: health
          volumeMounts:
            - name: config
              mountPath: /etc/telegraf
          startupProbe:
            httpGet:
              path: /
              port: 8888
          livenessProbe:
            httpGet:
              path: /
              port: 8888
          readinessProbe:
            httpGet:
              path: /
              port: 8888
      volumes:
        - name: config
          configMap:
            name: telegraf-config